### ISSUE TITLE
Update <Lithium> to <Nitrous Oxide>

### ISSUE THREAD

**Issue by utaninja** [TripSit/drugs#25]
I propose a modification of Lithium + Nitrous Oxide to say "Low risk + No Synergy"

I have been able to find no reason to think the combination is of concern, except for flagging by https://go.drugbank.com/drugs/DB14509 - but they tend to flag most interactions for CNS depression, and I am unable to find a report of concerns for CNS depression caused by Lithium.

I am creating an issue as I would like this to be reviewed and checked by someone else before submitting it. But I am fairly certain about this interaction.

**Comment by LunaUrsa** [comment]
I can make a pull request for this!

**Comment by LunaUrsa** [comment]
Ive made a draft pull request here that we can use in the future when this is confirmed: https://github.com/TripSit/drugs/pull/30

**Comment by LunaUrsa** [comment]
Removed that PR and made a new one, ready to merge once we're ready

**Comment by utaninja** [comment]
This seems reasonable and good to me. @LunaUrsa do you think a third person should review this or is this good to be resolved?

**Comment by LunaUrsa** [comment]
> This seems reasonable and good to me. @LunaUrsa do you think a third person should review this or is this good to be resolved?

If you're confident then that's good enough for me, if you think a third person is needed then i trust your judgement

I merged the change in this case!
