### ISSUE TITLE
DXM + Caffeine | Modification of the interaction

### ISSUE THREAD

**Issue by utaninja** [TripSit/drugs#3]
A suggestion by AlanaaBananaa has been to edit the current description of this combination, to include that it may cause increased blood pressure concerns in addition to heart rate.

Adding onto this, myself and ComedownKid agrees that this mixture can increase anxiety. I agree with the suggestion to move it to "caution"

**Comment by utaninja** [comment]
@AlanaaBlueLight

**Comment by AlanaaBlueLight** [comment]
@Electromorphosis 
@utaninja 
I'll in the meantime speak with psychonaut, as with us and them, we have TONS of anecdotal evidence, of caffeine + DXM being mostly an unpleasant experience, for many, and for some, just out right bad disso trip. 

Though actually amazing point out electro, with the cardiovascular hypertension risks. As that's right, it does potentiate stimulants over all actually reportedly on our forums, /r/drugs data, and psychonaut wiki's data of anecdotals. 

But I'll be back as soon as possible with more toxicology hubs reading more on this , and see if I can find anything more. 


The variability is also quite often reported in at least our side, on the anecdotal experiences.

**Comment by LunaUrsa** [comment]
Pull request ready for approval if we're good with this info

**Comment by utaninja** [comment]
> For DXM info about high pressure can be found here: https://pubmed.ncbi.nlm.nih.gov/22526529/ for caffeine e.g. https://pubmed.ncbi.nlm.nih.gov/21880846/ https://www.nature.com/articles/1600899 - caffeine posing risks to already hypertensive persons
> 
> However, there seems to be rather high variability in individual reactions to caffeine, e.g. possibly varying between habitual vs. occasional users: https://www.cambridge.org/core/journals/nutrition-research-reviews/article/caffeine-and-blood-pressure-a-critical-review-perspective/593DED6470D0EF70778667196777EAA7

I am good with having this changed to caution. While it does seem individual reactions vary with caffeine, generally from my understanding these combinations are going to have the basis where we do not take these kinds of things into account. Of course, if someone takes amphetamine daily, the concern of anxiety may be lowered due to the tolerance of the user. At the same time, arguably, it should take the basis of a blank slate user. It is good to note though it may be less of a concern for daily users. It seems this generally applies to a lot of cases (such as an individual taking daily ADHD meds and psychedelics, and so on)

I would be open to including a few trip reports of these combinations / some examples if we can find a lot of anecdotal evidence as @AlanaaBlueLight mentioned. @AlanaaBlueLight would you mind providing a few examples of these reports for the combination?
