### ISSUE TITLE
4mmc + MDMA

### ISSUE THREAD

**Issue by utaninja** [TripSit/drugs#52]
4mmc + MDMA

Dangerous

Risk of serotonin syndrome as both drugs raise serotonin levels. Stimulants also increase the neurotoxic effects of MDMA, in addition to concerns of high blood pressure and unnecessary strain on the heart. As well as potentially causing anxiety and greater physical discomfort due to the combination.

https://bpspubs.onlinelibrary.wiley.com/doi/10.1111/j.1476-5381.2011.01499.x
https://jpet.aspetjournals.org/content/339/2/530
https://pubmed.ncbi.nlm.nih.gov/1723797/
https://pubmed.ncbi.nlm.nih.gov/2881549/
https://pubmed.ncbi.nlm.nih.gov/11356903/
https://www.sciencedirect.com/science/article/abs/pii/S0091305701007110#:~:text=In%20the%20hot%20and%20crowded,emergencies%2C%20which%20occasionally%20prove%20fatal.
https://pubmed.ncbi.nlm.nih.gov/22037396/
https://link.springer.com/article/10.1007/BF00445556

**Comment by zelixir25** [comment]
For wording this maybe:
Both substances raise serotonin levels, leading to an increased risk of serotonin syndrome. Stimulants also increase the neurotoxic effects of MDMA while also creating additional strain on the heart and increased blood pressure. This combination may also increase anxiety and physical discomfort.
